### ISSUE TITLE
asdf install vim falied

### ISSUE THREAD

**Issue by vjunior1981** [tsuyoshicho/asdf-vim#9]
Hi there,

So, I'm trying to install a vim version using asdf, but I'm having a hard time:
```
asdf install vim 8.2.1059

...
...
checking whether stack_t has an ss_base field... no
checking --with-tlib argument... ncurses
checking for linking with ncurses library... OK
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.
```

I'm running OSX 11.1. If you need any more information, just le me know.

Any help would be appreciated :)

Best regards
Vitor Jr.

PS: thanks for this plugin!

**Comment by tsuyoshicho** [comment]
I see.
But work for later

**Comment by tsuyoshicho** [comment]
nothing response, close it.
